name: lyme_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  english_words: ^4.0.0
  provider: ^6.0.0
  mongo_dart: ^0.10.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_svg: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/icons/
    - lib/assets/images/
    - lib/data/repostiories/
    # - assets/data/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500




